apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: testci
  name: testci
spec:
  replicas: 5
  selector:
    matchLabels:
      app: testci
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: testci
    spec:
      containers:
        - image: 'logx1/testci:951bcbd'
          name: testci
          resources: {}
status: {}
