apiVersion: v1
kind: Service
metadata:
  labels:
    app: testci
  name: testci
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: testci
  type: LoadBalancer